version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/terminus-core"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/terminus-settings"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/terminus-terminal"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/terminus-community-color-schemes"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/terminus-plugin-manager"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/terminus-ssh"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
