pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
    - "status-success=Windows Build / Build"
    - "status-success=macOS Build / Build"
    - "status-success=Linux Build / Build"
    - "status-success=continuous-integration/appveyor/pr"
    - "#approved-reviews-by>=1"
    - "#changes-requested-reviews-by=0"
    - base=master
    actions:
      merge:
        method: merge
        strict: true
