language: node_js
node_js:
    - 7

cache:
  directories:
    - node_modules
    - app/node_modules

before_install:
    - npm i
    - scripts/install-deps.js

script:
    - scripts/build-native.js
    - npm run build
    - scripts/prepackage-plugins.js
    - scripts/build-linux.js

sudo: false

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/*.deb
    - dist/*.rpm
  skip_cleanup: true
  on:
    tags: true
