os:
  - linux
  - osx

language: node_js
node_js:
    - 7

cache:
  directories:
    - node_modules
    - app/node_modules

before_install:
    - npm i
    - scripts/install-deps.js

script:
    - scripts/build-native.js
    - npm run build
    - scripts/prepackage-plugins.js
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/build-linux.js; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/build-macos.js; fi

sudo: false

addons:
  apt:
    packages:
    - rpm

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/*.deb
    - dist/*.rpm
    - dist/*.tar.gz
    - dist/*.dmg
  skip_cleanup: true
  on:
    tags: true
