os: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: "7"

cache:
  - '%USERPROFILE%\.electron'

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - node scripts/install-deps.js
  - node scripts/build-native.js

build_script:
  - npm run build
  - node scripts/prepackage-plugins.js
  - node scripts/build-windows.js

deploy:
  provider: GitHub
  auth_token:
    secure: wvxHVlprvhfdOHgmVEDIwjCHYlmuDykteIEHpAfpi807+1lJD3ld2/OS6+0fgU4e
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
