trigger:
- master

variables:
- group: Vars

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn
    node scripts/build-native.js
    yarn run build:typings
    yarn run build
    node scripts/prepackage-plugins.js
    node scripts/build-windows.js
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'dist\\*.exe'
    artifactName: build
