trigger:
- master

variables:
- group: Vars

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: yarn
  displayName: 'Install dependencies'

- script: node scripts/build-native.js
  displayName: 'Rebuild native dependencies'

- script: yarn run build:typings
  displayName: 'Build typings'

- script: yarn run build
  displayName: 'Build'

- script: node scripts/prepackage-plugins.js
  displayName: 'Prepackage plugins'

- script: node scripts/build-windows.js
  displayName: 'Package'

- task: CopyFiles@2
  inputs:
    contents: 'dist\\*.exe'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Build
