trigger:
- master

variables:
- group: Vars

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: yarn
  displayName: 'Install dependencies'

- script: node scripts/build-native.js
  displayName: 'Rebuild native dependencies'

- script: yarn run build:typings
  displayName: 'Build typings'

- script: yarn run build
  displayName: 'Build'

- script: node scripts/prepackage-plugins.js
  displayName: 'Prepackage plugins'

- script: node scripts/build-windows.js
  displayName: 'Package'
  env:
    WIN_CSC_LINK: $(WIN_CSC_LINK)
    WIN_CSC_KEY_PASSWORD: $(WIN_CSC_KEY_PASSWORD)
    BT_TOKEN: $(BT_TOKEN)
    GH_TOKEN: $(GH_TOKEN)

- task: CopyFiles@2
  inputs:
    contents: 'dist\\*-setup.exe'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Windows - Installer

- task: CopyFiles@2
  inputs:
    contents: 'dist\\*-portable.exe'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Windows - Portable build
