hotkeys:
  new-window:
    - 'Ctrl-Shift-N'
  toggle-window:
    - 'Ctrl+Space'
  toggle-fullscreen:
    - 'F11'
  close-tab:
    - 'Ctrl-Shift-W'
    - ['Ctrl-A', 'K']
  toggle-last-tab:
    - ['Ctrl-A', 'A']
    - ['Ctrl-A', 'Ctrl-A']
  next-tab:
    - 'Ctrl-Shift-ArrowRight'
    - ['Ctrl-A', 'N']
    - 'Ctrl-Tab'
  previous-tab:
    - 'Ctrl-Shift-ArrowLeft'
    - ['Ctrl-A', 'P']
    - 'Ctrl-Shift-Tab'
  tab-1:
    - 'Alt-1'
    - ['Ctrl-A', '1']
  tab-2:
    - 'Alt-2'
    - ['Ctrl-A', '2']
  tab-3:
    - 'Alt-3'
    - ['Ctrl-A', '3']
  tab-4:
    - 'Alt-4'
    - ['Ctrl-A', '4']
  tab-5:
    - 'Alt-5'
    - ['Ctrl-A', '5']
  tab-6:
    - 'Alt-6'
    - ['Ctrl-A', '6']
  tab-7:
    - 'Alt-7'
    - ['Ctrl-A', '7']
  tab-8:
    - 'Alt-8'
    - ['Ctrl-A', '8']
  tab-9:
    - 'Alt-9'
    - ['Ctrl-A', '9']
  tab-10:
    - 'Alt-0'
    - ['Ctrl-A', '0']
pluginBlacklist: []
