hotkeys:
  toggle-window:
    - 'Ctrl+Space'
  close-tab:
    - '⌘-W'
    - ['Ctrl-A', 'K']
  toggle-last-tab:
    - ['Ctrl-A', 'A']
    - ['Ctrl-A', 'Ctrl-A']
  next-tab:
    - '⌘-ArrowRight'
    - ['Ctrl-A', 'N']
    - 'Ctrl-Tab'
  previous-tab:
    - '⌘-ArrowLeft'
    - ['Ctrl-A', 'P']
    - 'Ctrl-Shift-Tab'
  tab-1:
    - '⌘-1'
    - ['Ctrl-A', '1']
  tab-2:
    - '⌘-2'
    - ['Ctrl-A', '2']
  tab-3:
    - '⌘-3'
    - ['Ctrl-A', '3']
  tab-4:
    - '⌘-4'
    - ['Ctrl-A', '4']
  tab-5:
    - '⌘-5'
    - ['Ctrl-A', '5']
  tab-6:
    - '⌘-6'
    - ['Ctrl-A', '6']
  tab-7:
    - '⌘-7'
    - ['Ctrl-A', '7']
  tab-8:
    - '⌘-8'
    - ['Ctrl-A', '8']
  tab-9:
    - '⌘-9'
    - ['Ctrl-A', '9']
  tab-10:
    - '⌘-0'
    - ['Ctrl-A', '0']
pluginBlacklist: ['ssh']
