name: Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Installing Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 15

    - name: Install deps
      run: |
        npm i -g yarn@1.19.1
        cd app
        yarn
        cd ..
        rm app/node_modules/.yarn-integrity
        yarn

    - name: Build typings
      run: yarn run build:typings

    - name: Lint
      run: yarn run lint
