name: Linux Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Installing Node
      uses: actions/setup-node@v1
      with:
        version: 10

    - name: Install deps
      run: |
        cd app
        yarn
        cd ..
        rm app/node_modules/.yarn-integrity
        yarn

    - name: Lint
      run: yarn run lint

    - name: Build native deps
      run: scripts/build-native.js

    - name: Build
      run: |
        yarn run build:typings
        yarn run build

    - name: Build packages
      run: |
        scripts/prepackage-plugins.js
        DEBUG=electron-builder scripts/build-linux.js
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Package artifacts
      run: |
        mkdir artifact-deb
        mv dist/*.deb artifact-deb/
        mkdir artifact-rpm
        mv dist/*.rpm artifact-rpm/
        mkdir artifact-snap
        mv dist/*.snap artifact-snap/
        mkdir artifact-tar.gz
        mv dist/*.tar.gz artifact-tar.gz/

    - uses: actions/upload-artifact@master
      name: Upload DEB
      with:
        name: Linux .deb
        path: artifact-deb

    - uses: actions/upload-artifact@master
      name: Upload RPM
      with:
        name: Linux .rpm
        path: artifact-rpm

    - uses: actions/upload-artifact@master
      name: Upload Snap
      with:
        name: Linux .snap
        path: artifact-snap

    - uses: actions/upload-artifact@master
      name: Upload tarball
      with:
        name: Linux tarball
        path: artifact-tar.gz
