name: macOS Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Installing Node
      uses: actions/setup-node@v1
      with:
        version: 10

    - name: Build
      run: build/travis.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        BT_TOKEN: ${{ secrets.BT_TOKEN }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

    - name: Package artifacts
      run: |
        mkdir artifact
        mv dist/*.pkg dist/*.zip artifact/

    - uses: actions/upload-artifact@master
      with:
        name: macOS build
        path: artifact
