name: macOS Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Installing Node
      uses: actions/setup-node@v1
      with:
        version: 10

    - name: Build
      run: |
        cd app
        yarn
        cd ..
        rm app/node_modules/.yarn-integrity
        yarn
        scripts/build-native.js
        yarn run build:typings
        yarn run build
        scripts/prepackage-plugins.js
        scripts/build-macos.js
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        BT_TOKEN: ${{ secrets.BT_TOKEN }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

    - name: Package artifacts
      run: |
        mkdir artifact-pkg
        mv dist/*.pkg artifact-pkg/
        mkdir artifact-zip
        mv dist/*.zip artifact-zip/

    - uses: actions/upload-artifact@master
      name: Upload PKG
      with:
        name: macOS .pkg
        path: artifact-pkg

    - uses: actions/upload-artifact@master
      name: Upload ZIP
      with:
        name: macOS .zip
        path: artifact-zip
