name: Windows Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2016

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Installing Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14

    - name: Build
      shell: powershell
      run: |
        npm i -g yarn@1.19.1
        yarn
        node scripts/build-native.js
        yarn run build
        node scripts/prepackage-plugins.js

    - name: Build and sign packages
      run: node scripts/build-windows.js
      if: github.repository == 'Eugeny/terminus' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags'))
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
        WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
        # DEBUG: electron-builder,electron-builder:*

    - name: Build packages without signing
      run: node scripts/build-windows.js
      if: "!(github.repository == 'Eugeny/terminus' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')))"

    - name: Upload symbols
      run: |
        npm install @sentry/cli
        node scripts/sentry-upload.js
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    - name: Package artifacts
      run: |
        mkdir artifact-setup
        mv dist/*-setup.exe artifact-setup/
        mkdir artifact-portable
        mv dist/*-portable.zip artifact-portable/

    - uses: actions/upload-artifact@master
      name: Upload installer
      with:
        name: Installer
        path: artifact-setup

    - uses: actions/upload-artifact@master
      name: Upload portable build
      with:
        name: Portable build
        path: artifact-portable
